[package]
name = "rustls-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
rustls = "0.21.0-alpha.1"
rustls-native-certs = "0.6.2"
rustls-pemfile = "1.0.2"
